#!usr/bin/env julia

################## Librairies ####################
using ITensors
using ITensorMPS
using LinearAlgebra

################## Functions #####################

"""
N -- number of sites 
J -- coupling constant
h -- disorder constant

Define the operator expτ(-JSS - hSz)
"""
function ITensors.op(::OpName"expτSS", ::SiteType"S=1/2", s1::Index, s2::Index; τ, h)
    H =
        -1 / 2 * op("S+", s1) * op("S-", s2) +
        -1 / 2 * op("S-", s1) * op("S+", s2)
    -h * op("Sz", s1) * op("Sz", s2)
    return exp(τ * H)
end

"""
N -- number of sites 
J -- coupling constant
h -- disorder constant

return the Trotter Suzuki gates (order 2) and the Hamiltonian to compute TEBD and energy
"""
function gateTrotterSuzukiandhamiltonian(N, h, δτ, parity::String)
    s = ITensors.siteinds("S=1/2", N)
    if mod(N, 2) == 0
        if parity == "even"
            gates = ops([("expτSS", (n, n + 1), (τ=-δτ / 2, h=h,)) for n in 1:(N-1)], s)
        elseif parity == "odd"
            gates = ops([("expτSS", (n, n + 1), (τ=-δτ, h=h,)) for n in 2:(N-2)], s)
        end
    elseif mod(N, 2) == 1
        if parity == "even"
            gates = ops([("expτSS", (n, n + 1), (τ=-δτ / 2, h=h,)) for n in 2:(N-2)], s)
        elseif parity == "odd"
            gates = ops([("expτSS", (n, n + 1), (τ=-δτ, h=h,)) for n in 1:(N-1)], s)
        end
    end
    @show typeof(gates)
    append!(gates, reverse(gates))
    ampo = AutoMPO()
    for j in 1:N-1
        add!(ampo, -1 / 2, "S+", j, "S-", j + 1)
        add!(ampo, -1 / 2, "S-", j, "S+", j + 1)
        add!(ampo, -1 / 2, "Sz", j, "Sz", j + 1)
        add!(ampo, -h, "Sz", j)
    end
    add!(ampo, -h, "Sz", N)
    H = MPO(ampo, s)
    return gates, H, s
end
"""
exact energy of the 1D Heisenberg Hamiltonian ground state
"""
function exactgroundenergy(J=1)
    return J * (1 / 4 - log(2))
end

"""
psi -- MPS converged on which you make the measurement 
n -- site measure

return the Sz value on the site n 
"""
function measure_Sz(psi::MPS, n)
    psi = orthogonalize(psi, n)
    sn = siteind(psi, n)
    Sz = scalar(dag(prime(psi[n], "Site")) * op("Sz", sn) * psi[n])
    return real(Sz)
end

"""
psi -- MPS converged on which you make the measurement 
n -- site measure
H -- hamiltonian

WARNING: psi and H have to be compatible that means they have to be generated by the functions in this file

return the expectation value of H on site n
"""
function measure_H(psi, n, H)
    orthogonalize!(psi, n)
    e = inner(psi, H, psi)
    return e
end

"""
s -- sites index
D -- bond dimension 

return an randmoly initialized MPS with the sites indexes in input 
"""
function random_initialized_MPS(s, D)
    psi = random_mps(s, linkdims=D)
    return psi
end

"""
nsweep -- number of sweeps
mps -- initial mps
gates -- even and odd you want to apply
cutoff -- cutoff in the truncation part in the applying gate process

return the converged mps with n sweeps along the mps
"""
function tebd!(nsweep, mps, gateseven, gatesodd, cutoff)
    for i in 1:nsweep
        mps = apply(gateseven, mps; cutoff)
        normalize!(mps)
        mps = apply(gatesodd, mps; cutoff)
        normalize!(mps)
    end
end

